This dataset is collected from the National Health Insurance Service in Korea. All personal information and sensitive data were excluded.
1. The purpose of this dataset is to classify Drinker or Not.
2. Perform KKN & Decision Tree Classifier.
3. Evaluate Both ML Models by Confusion Matrix and Relevant Performance Parameters.

In [19]:
import numpy as np
import pandas as pd

In [20]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [21]:
df = pd.read_csv('/content/drive/MyDrive/smoking_driking_dataset_Ver01/smoking_driking_dataset_Ver01.csv')

In [22]:
df1 = df.copy()
df2 = df.copy()
df3 = df.copy()

In [23]:
df.shape

(991346, 24)

In [24]:
df.head()

sex  age  height  weight  waistline  sight_left  sight_right  hear_left  \
0  Male   35     170      75       90.0         1.0          1.0        1.0   
1  Male   30     180      80       89.0         0.9          1.2        1.0   
2  Male   40     165      75       91.0         1.2          1.5        1.0   
3  Male   50     175      80       91.0         1.5          1.2        1.0   
4  Male   50     165      60       80.0         1.0          1.2        1.0   

   hear_right    SBP   DBP   BLDS  tot_chole  HDL_chole  LDL_chole  \
0         1.0  120.0  80.0   99.0      193.0       48.0      126.0   
1         1.0  130.0  82.0  106.0      228.0       55.0      148.0   
2         1.0  120.0  70.0   98.0      136.0       41.0       74.0   
3         1.0  145.0  87.0   95.0      201.0       76.0      104.0   
4         1.0  138.0  82.0  101.0      199.0       61.0      117.0   

   triglyceride  hemoglobin  urine_protein  serum_creatinine  SGOT_AST  \
0          92.0        17.1            1.0               1.0      21.0   
1         121.0        15.8            1.0               0.9      20.0   
2         104.0        15.8            1.0               0.9      47.0   
3         106.0        17.6            1.0               1.1      29.0   
4         104.0        13.8            1.0               0.8      19.0   

   SGOT_ALT  gamma_GTP  SMK_stat_type_cd DRK_YN  
0      35.0       40.0               1.0      Y  
1      36.0       27.0               3.0      N  
2      32.0       68.0               1.0      N  
3      34.0       18.0               1.0      N  
4      12.0       25.0               1.0      N

In [60]:
df.columns

Index(['sex', 'age', 'height', 'weight', 'waistline', 'sight_left',
       'sight_right', 'hear_left', 'hear_right', 'SBP', 'DBP', 'BLDS',
       'tot_chole', 'HDL_chole', 'LDL_chole', 'triglyceride', 'hemoglobin',
       'urine_protein', 'serum_creatinine', 'SGOT_AST', 'SGOT_ALT',
       'gamma_GTP', 'SMK_stat_type_cd', 'DRK_YN'],
      dtype='object')

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 991346 entries, 0 to 991345
Data columns (total 24 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   sex               991346 non-null  object 
 1   age               991346 non-null  int64  
 2   height            991346 non-null  int64  
 3   weight            991346 non-null  int64  
 4   waistline         991346 non-null  float64
 5   sight_left        991346 non-null  float64
 6   sight_right       991346 non-null  float64
 7   hear_left         991346 non-null  float64
 8   hear_right        991346 non-null  float64
 9   SBP               991346 non-null  float64
 10  DBP               991346 non-null  float64
 11  BLDS              991346 non-null  float64
 12  tot_chole         991346 non-null  float64
 13  HDL_chole         991346 non-null  float64
 14  LDL_chole         991346 non-null  float64
 15  triglyceride      991346 non-null  float64
 16  hemoglobin        99

In [26]:
print(df.isnull().sum())

sex                 0
age                 0
height              0
weight              0
waistline           0
sight_left          0
sight_right         0
hear_left           0
hear_right          0
SBP                 0
DBP                 0
BLDS                0
tot_chole           0
HDL_chole           0
LDL_chole           0
triglyceride        0
hemoglobin          0
urine_protein       0
serum_creatinine    0
SGOT_AST            0
SGOT_ALT            0
gamma_GTP           0
SMK_stat_type_cd    0
DRK_YN              0
dtype: int64


In [27]:
print(df.nunique())

sex                    2
age                   14
height                13
weight                24
waistline            737
sight_left            24
sight_right           24
hear_left              2
hear_right             2
SBP                  171
DBP                  127
BLDS                 498
tot_chole            474
HDL_chole            223
LDL_chole            432
triglyceride        1657
hemoglobin           190
urine_protein          6
serum_creatinine     183
SGOT_AST             568
SGOT_ALT             594
gamma_GTP            940
SMK_stat_type_cd       3
DRK_YN                 2
dtype: int64


In [29]:
pd.set_option('display.max_columns',None)
df1.head()

sex  age  height  weight  waistline  sight_left  sight_right  hear_left  \
0  Male   35     170      75       90.0         1.0          1.0        1.0   
1  Male   30     180      80       89.0         0.9          1.2        1.0   
2  Male   40     165      75       91.0         1.2          1.5        1.0   
3  Male   50     175      80       91.0         1.5          1.2        1.0   
4  Male   50     165      60       80.0         1.0          1.2        1.0   

   hear_right    SBP   DBP   BLDS  tot_chole  HDL_chole  LDL_chole  \
0         1.0  120.0  80.0   99.0      193.0       48.0      126.0   
1         1.0  130.0  82.0  106.0      228.0       55.0      148.0   
2         1.0  120.0  70.0   98.0      136.0       41.0       74.0   
3         1.0  145.0  87.0   95.0      201.0       76.0      104.0   
4         1.0  138.0  82.0  101.0      199.0       61.0      117.0   

   triglyceride  hemoglobin  urine_protein  serum_creatinine  SGOT_AST  \
0          92.0        17.1            1.0               1.0      21.0   
1         121.0        15.8            1.0               0.9      20.0   
2         104.0        15.8            1.0               0.9      47.0   
3         106.0        17.6            1.0               1.1      29.0   
4         104.0        13.8            1.0               0.8      19.0   

   SGOT_ALT  gamma_GTP  SMK_stat_type_cd DRK_YN  
0      35.0       40.0               1.0      Y  
1      36.0       27.0               3.0      N  
2      32.0       68.0               1.0      N  
3      34.0       18.0               1.0      N  
4      12.0       25.0               1.0      N

In [30]:
df['DRK_YN'].value_counts()

N    495858
Y    495488
Name: DRK_YN, dtype: int64

In [31]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [32]:
from pandas.core.dtypes.common import is_numeric_dtype

In [33]:
for col in df1.columns:
    if is_numeric_dtype(df1[col]):
        continue
    else:
        df1[col] = le.fit_transform(df1[col])

In [36]:
df1.tail()

sex  age  height  weight  waistline  sight_left  sight_right  \
991341    1   45     175      80       92.1         1.5          1.5   
991342    1   35     170      75       86.0         1.0          1.5   
991343    0   40     155      50       68.0         1.0          0.7   
991344    1   25     175      60       72.0         1.5          1.0   
991345    1   50     160      70       90.5         1.0          1.5   

        hear_left  hear_right    SBP   DBP  BLDS  tot_chole  HDL_chole  \
991341        1.0         1.0  114.0  80.0  88.0      198.0       46.0   
991342        1.0         1.0  119.0  83.0  83.0      133.0       40.0   
991343        1.0         1.0  110.0  70.0  90.0      205.0       96.0   
991344        1.0         1.0  119.0  74.0  69.0      122.0       38.0   
991345        1.0         1.0  133.0  79.0  99.0      225.0       39.0   

        LDL_chole  triglyceride  hemoglobin  urine_protein  serum_creatinine  \
991341      125.0         132.0        15.0            1.0               1.0   
991342       84.0          45.0        15.8            1.0               1.1   
991343       77.0         157.0        14.3            1.0               0.8   
991344       73.0          53.0        14.5            1.0               0.8   
991345      153.0         163.0        15.8            1.0               0.9   

        SGOT_AST  SGOT_ALT  gamma_GTP  SMK_stat_type_cd  DRK_YN  
991341      26.0      36.0       27.0               1.0       0  
991342      14.0      17.0       15.0               1.0       0  
991343      30.0      27.0       17.0               3.0       1  
991344      21.0      14.0       17.0               1.0       0  
991345      24.0      43.0       36.0               3.0       1

**Training and Testing Sets**

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
X = df1.drop('DRK_YN', axis=1)
Y = df1['DRK_YN']

In [39]:
Xtrain , Xtest, ytrain, ytest = train_test_split(X, Y ,test_size=0.3, random_state=42)

In [40]:
Xtrain.shape

(693942, 23)

In [41]:
Xtest.shape

(297404, 23)

K-Nearest Neighbors (KNN)

In [42]:
from sklearn.neighbors import KNeighborsClassifier

In [43]:
knn = KNeighborsClassifier(n_neighbors=833)

In [44]:
knn.fit(Xtrain, ytrain)

KNeighborsClassifier(n_neighbors=833)

In [45]:
knn_predictions = knn.predict(Xtest)

 Evaluate the Models

In [46]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report

# Evaluate the KNN model
knn_accuracy = accuracy_score(ytest, knn_predictions)
knn_precision_score = precision_score(ytest, knn_predictions)
knn_recall_score = recall_score(ytest, knn_predictions)
knn_cm = confusion_matrix(ytest, knn_predictions)
knn_classification_report = classification_report(ytest, knn_predictions)

In [58]:
print("K-Nearest Neighbors Accuracy score:")
print(knn_accuracy)
print("\nK-Nearest Neighbors Precision score:")
print(knn_precision_score)
print("\nK-Nearest Neighbors Recall score:")
print(knn_recall_score)
print("\nK-Nearest Neighbors Confusion Matrix:")
print(knn_cm)
print("\nK-Nearest Neighbors Classification Report:")
print(knn_classification_report)

K-Nearest Neighbors Accuracy score:
0.7038506543287918

K-Nearest Neighbors Precision score:
0.6979625134045171

K-Nearest Neighbors Recall score:
0.7155884713706604

K-Nearest Neighbors Confusion Matrix:
[[103237  45910]
 [ 42166 106091]]

K-Nearest Neighbors Classification Report:
              precision    recall  f1-score   support

           0       0.71      0.69      0.70    149147
           1       0.70      0.72      0.71    148257

    accuracy                           0.70    297404
   macro avg       0.70      0.70      0.70    297404
weighted avg       0.70      0.70      0.70    297404



**Decision Tree Classifier**

In [50]:
from sklearn.tree import DecisionTreeClassifier

# Create and train the Decision Tree classifier
decision_tree = DecisionTreeClassifier(random_state=42)
decision_tree.fit(Xtrain, ytrain)

DecisionTreeClassifier(random_state=42)

In [51]:
# Make predictions on the testing data
dt_predictions = decision_tree.predict(Xtest)

In [54]:
# Evaluate the Decision Tree model
dt_accuracy = accuracy_score(ytest, dt_predictions)
dt_precision_score = precision_score(ytest, dt_predictions)
dt_recall_score = recall_score(ytest, dt_predictions)
dt_cm = confusion_matrix(ytest, dt_predictions)
dt_classification_report = classification_report(ytest, dt_predictions)

In [57]:
print("Decision Tree Accuracy score:")
print(dt_accuracy)
print("\nDecision Tree Precision score:")
print(dt_precision_score)
print("\nDecision Tree Recall score:")
print(dt_recall_score)
print("\nDecision Tree Confusion Matrix:")
print(dt_cm)
print("\nDecision Tree Classification Report:")
print(dt_classification_report)

Decision Tree Accuracy score:
0.6454587026401797

Decision Tree Precision score:
0.6438743758106901

Decision Tree Recall score:
0.6462022029313962

Decision Tree Confusion Matrix:
[[96158 52989]
 [52453 95804]]

Decision Tree Classification Report:
              precision    recall  f1-score   support

           0       0.65      0.64      0.65    149147
           1       0.64      0.65      0.65    148257

    accuracy                           0.65    297404
   macro avg       0.65      0.65      0.65    297404
weighted avg       0.65      0.65      0.65    297404



In [56]:
print("K-Nearest Neighbors Confusion Matrix:")
print(knn_cm)
print("K-Nearest Neighbors Classification Report:")
print(knn_classification_report)

print("\nDecision Tree Confusion Matrix:")
print(dt_cm)
print("Decision Tree Classification Report:")
print(dt_classification_report)

K-Nearest Neighbors Confusion Matrix:
[[103237  45910]
 [ 42166 106091]]
K-Nearest Neighbors Classification Report:
              precision    recall  f1-score   support

           0       0.71      0.69      0.70    149147
           1       0.70      0.72      0.71    148257

    accuracy                           0.70    297404
   macro avg       0.70      0.70      0.70    297404
weighted avg       0.70      0.70      0.70    297404


Decision Tree Confusion Matrix:
[[96158 52989]
 [52453 95804]]
Decision Tree Classification Report:
              precision    recall  f1-score   support

           0       0.65      0.64      0.65    149147
           1       0.64      0.65      0.65    148257

    accuracy                           0.65    297404
   macro avg       0.65      0.65      0.65    297404
weighted avg       0.65      0.65      0.65    297404

